# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en"
title                    : "Your Site Title"
title_separator          : "-"
name                     : "Your Name"
description              : "Your personal description"
url                      : "https://yourdomain.com" # the base hostname & protocol for your site
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "yourusername/yourrepository"

# Site Author
author:
  avatar           : "your-avatar.png"
  name             : "Your Name"
  bio              : "Your short biography"
  location         : "Your Location"
  employer         : "Your Employer"
  uri              : ""
