# _config.yml

# Site settings
title: Your Academic Website
description: Welcome to my academic website!

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-scholar

# Personal information
author:
  name: Your Name
  bio: PhD Candidate in Computer Science
  location: City, Country
  email: your.email@example.com
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/yourusername
    - label: Twitter
      icon: fab fa-twitter
      url: https://twitter.com/yourtwitter

# Scholar settings
scholar:
  language: "en"
  bibliography: "your-bibliography.bib"
  sort_by: "year"
  order: "descending"
