# -------------------- #
#      Config.yml      #
# -------------------- #

# Site Basics
title: "Arduino Tomasi"
name: "Arduino Tomasi"
description: "personal description"
url: "https://arduinotomasi.github.io"
baseurl: ""
locale: "en-US"

# Jekyll & Build
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
include: ["_pages"]
exclude: ["node_modules", "Gemfile.lock", "vendor"]

# Autor
author:
  name: "Arduino Tomasi"
  avatar: "photo.png"
  github: "arduinotomasi"
  orcid: "http://orcid.org/0000-0001-5852-0728"
  twitter: "ArduinoTomasi"

# Colecciones (solo necesarias para Research si usas colección)
collections:
  research:
    output: true
    permalink: /research/:path/

# Defaults (solo para páginas/posts)
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true

# Blog Config
permalink: /blog/:year/:title/
paginate: 5
paginate_path: /blog/page:num/

# SEO & Social
social:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/arduinotomasi"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "http://orcid.org/0000-0001-5852-0728"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/ArduinoTomasi"

google_site_verification: wIug60jUddg2K4FLuMzN-57Zea-AqH5K-AI4LzsSSzk
twitter:
  username: "ArduinoTomasi"

# -------------------- #
#    Estructura Final  #
# -------------------- #
# Páginas requeridas:
# - _pages/research.md       -> /research/
# - _pages/Pax.md            -> /Pax/
# - _pages/year-archive.md   -> /year-archive/