# Site Settings
locale                   : "en-US"
title                    : "Hyunwoo Kwon"
title_separator          : "-"
name                     : &name "Hyunwoo Kwon"
description              : &description "Prospective Graduate Student in Mechanical Engineering"
url                      : https://hwkwon1114.github.io
baseurl                  : ""
repository               : "hwkwon1114/hwkwon1114.github.io"
teaser                   : 
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Analytics
analytics:  
  provider               : false

# Site Author
author:
  name             : "Hyunwoo Kwon"
  avatar           : "/images/My Pic.jpg"
  bio              : "Prospective Graduate Student in Mechanical Engineering"
  location         : "512 E Stoughton St Apt 310, Champaign, IL 61820"
  email            : hwkwon1114@gmail.com
  research_interests: "Computational Mechanics"
  skills           : "C++, Python, Matlab, COMSOL, SolidWorks, ANSYS, Abaqus"
  github           : "hwkwon1114"
  linkedin         : "hwkwon1114"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  research_experience:
    output: true
    permalink: /:collection/:path/
  
  conferences:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _research_experience
  - scope:
      path: ""
      type: research_experience
    values:
      layout: single
      author_profile: true
      share: true
  # _conferences
  - scope:
      path: ""
      type: conferences
    values:
      layout: single
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Chicago

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

