
# Site configuration

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
author: RachaelPhillips
google_analytics: "G-154731139"
disqus: "adventurewithrachael"

twitter:
  username: adventurerachael

social:
  name: Rachael Phillips
  links:
    - https://twitter.com/adventurerachael
    - https://www.instagram.com/adventurewithrachael/
    - https://www.linkedin.com/in/rachael-phillips-data-expert
    - https://github.com/rachaelph

markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: America/New_York

# 5. Collections
collections:
  posts:
    title: Adventures Around the World
    output: true
    description: "Adventures Around the World"
    feature_image: "https://picsum.photos/1300/400?image=197"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: "posts"
    values:
      image: "https://picsum.photos/1300/400?image=197"
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page

# 7. Site settings
encoding: utf-8
lang: en-GB
title: "Adventure With Rachael"
logo: "/assets/logos/logo.svg"
description: "Join Rachael on global adventures, personal wellness journeys, and deep dives into all things data and creativity."
url: "https://adventurewithrachael.com"
baseurl: ""
repo: "https://github.com/rachaelph/rachaelph.github.io"
email: "rachael.phillips23@gmail.com"
css_inline: true

# 8. Site favicons & manifest icons
favicons:
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Travel
  url: /aroundtheworld/
- title: Wellness
  url: /healthandwellness/
- title: Data & AI
  url: /allthingsdata/
- title: Music (Avenue 42)
  url: /avenue42/
- title: Book Reviews
  url: /books/

navigation_footer:
- title: Edited by Rachael Phillips
  url: https://adventurewithrachael.com

social_links:
  LinkedIn: https://www.linkedin.com/in/rachael-phillips-data-expert
  GitHub: https://github.com/rachaelph
  link: https://adventurewithrachael.com

sharing_links:
  facebook: "#3B5998"
  Email: true

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap
    - https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&display=swap
    # No direct Google Font for Segoe UI, so it's added as a system font fallback.
    # The next step includes updating the CSS.
