# Basic Site Settings
title: "孔梓鲲 | 金融科技个人主页"
name: &name "孔梓鲲"
description: &description "深圳大学金融科技专业本科生，关注量化金融、AI与行为研究"
url: "https://kongzikun.github.io" # 改成你的 GitHub Pages 地址
baseurl: ""
repository: "kongzikun/kongzikun.github.io"

# Site Author
author:
  avatar: "profile.png" # 上传你头像文件并放进 /images 或 /assets/img
  name: "孔梓鲲"
  bio: "深圳大学金融科技本科生 | 聚焦金融AI、行为分析与因子建模"
  location: "中国·深圳"
  employer: "深圳大学"
  email: "kongzikun@outlook.com"
  researchgate: "" # 如果你有学术主页可以填
  orcid: ""
  github: "kongzikun" # GitHub 用户名
  linkedin: ""           # 如果有 LinkedIn
  

# Publication Category（默认保留）
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Analytics（如不使用可以保留 false）
analytics:
  provider: "false"

# Language & SEO
locale: "zh-CN"
timezone: Asia/Shanghai

# Social sharing / Open Graph
og_image: "/images/profile.png"
twitter:
  username: "" # 如果你有 X / Twitter 可填

# Markdown 和渲染设置可不动
