# Site settings
title: "Renjith K Nair"
email: "your.email@example.com"
description: "Digital Transformation Graduate | Aspiring SOC Analyst"
url: "https://renjithknair2203.github.io"  # Your GitHub Pages URL
baseurl: "/"  # The base URL for your site
logo: "/assets/images/logo.png"  # Optional: Add a logo image to the header

# Social Media Links
social_links:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/renjithknair/"
  - name: "GitHub"
    url: "https://github.com/renjithknair2203"
  - name: "Twitter"
    url: "https://twitter.com/renjithknair"
  - name: "Email"
    url: "mailto:your.email@example.com"

# Content settings
paginate: 5  # Number of posts per page
paginate_path: "/page:num"  # Pagination format
show_excerpts: true  # Show excerpts of posts on the homepage

# Navigation menu settings
navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

# Include specific content (optional)
# Uncomment the lines below if you want to show the sections on your website
# about: true
# projects: true
# talks: true
# publications: true
# teaching: true

# Optional settings for custom themes
theme: "minimal-mistakes"  # Minimal Mistakes theme for styling
theme_navigation: true  # Enable navigation menu in theme
