# Welcome to Jekyll!

# This config file is for settings that affect your entire site.
# Set up once and edit rarely. Restart the server process after changes.

# Site Settings
locale                   : "en-US"
title                    : "Tianyang Wang's Academic Portfolio"
title_separator          : " | "
name                     : "Tianyang Wang"
description              : "Dedicated to advancing the field of medical imaging through innovative computer vision research."
url                      : "https://tianyang-wang35.github.io/"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "academicpages/academicpages.github.io"

# Author Profile
author:
  avatar                 : "profile.png"
  name                   : "Tianyang Wang"
  bio                    : "Third-year undergrad at the School of AI and Advanced Computing, Xi'an Jiaotong-Liverpool University, specializing in medical imaging."
  location               : "Shanghai, China"
  employer               : "Xi'an Jiaotong-Liverpool University"
  email                  : "Tianyang.Wang21@student.xjtlu.edu.cn"
  googlescholar          : "https://scholar.google.com/citations?user=057tu_4AAAAJ"

# Enhancements
breadcrumbs             : true
words_per_minute        : 180
future                  : true
read_more               : "enabled"
comments:
  provider              : "disqus"
  disqus:
    shortname           : "yourshortname"

# SEO Setup
google_site_verification: "your_google_verification_code"
bing_site_verification  : "your_bing_verification_code"
alexa_site_verification : "your_alexa_verification_code"
yandex_site_verification: "your_yandex_verification_code"

# Social Media
twitter:
  username              : "yourTwitterHandle"

# Analytics
analytics:
  provider              : "google-universal"
  google:
    tracking_id         : "UA-XXXXXXXXX-X"

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections
collections:
  publications:
    output: true
    permalink: "/publications/:path/"
  portfolio:
    output: true
    permalink: "/portfolio/:path/"
  talks:
    output: true
    permalink: "/talks/:path/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_profile: true
      share: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author_profile: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed

# Permalinks
permalink: "/:categories/:title/"

# Time Zone
timezone: "Asia/Shanghai"

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
