version: '3.8'

services:
  mywebsite:
    build: ..
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: ["jekyll", "serve", "-H", "0.0.0.0", "-w", "--config", "_config.dev.yml,_config.yml"]