version: '3.8'

services:
  # Production web service
  web:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped

  # Development service with hot reload
  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: >
      ssh -c "
                    npm install &&
                    npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      - NODE_ENV=development

volumes:
  node_modules: