name: Deploy Jekyll Site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Site
      env:
        FORMSPREE_API_URL: ${{ secrets.FORMSPREE_API_URL }}
      run: |
        bundle exec jekyll build --trace
        echo "forms_api: $FORMSPREE_API_URL" >> _config.yml

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
