name: jekyll-cd

on:
  push:
    branches:
      - deployed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🧪 Build and deploy
        uses: peterjsadowski/jekyll-cd@master
